### ISSUE TITLE
Prepare for Byzantium hardfork

### ISSUE THREAD

**Issue by mersinvald** [ETCDEVTeam/sputnikvm#343]
[Byzantium ECIP](https://github.com/ethereumproject/ECIPs/blob/8474c478f7848e7d9825b5045194a837303e78dc/ECIPs/ECIP-1045.md)

- [x] [STATICCALL](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-214.md)
- [x] [REVERT](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md)
- [x] [RETURNDATACOPY, 
RETURNDATASIZE](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-211.md)
- [x] Byzantium precompiled contracts
- [ ] Extensive testing

**Comment by mersinvald** [comment]
Also need to fix Byzantium precompiled contracts so they would compile with `#[no_std]` #333

**Comment by mersinvald** [comment]
This issue was moved to etclabscore/sputnikvm#5
